# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-21 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='users',
            field=models.ManyToManyField(related_name='trips1', to='exam.User'),
        ),
    ]
